export let glossarydata = {
    "Address Delegation": "Delegation of a wallet's stake to a Super Staker",
    "Airdrop": "A way to promote cryptocurrencies by sending some free tokens to traders",
    "Algorithm": "A set of rules to follow to solve a problem or conduct a task",
    "Algorithmic Stablecoin": "Tokens pegged to a fiat currency through software and specific conditions",
    "All-Time-High (ATH)": "The highest point (in price, in market capitalization) that a cryptocurrency has been in history",
    "All-Time-Low (ATL)": "The lowest point (in price, in market capitalization) that a cryptocurrency has been in history",
    "Altcoin": "Coins alternative to Bitcoin",
    "Application Programming Interface (API)": "Software that acts like an intermediary allowing applications to interact",
    "Application-Specific Integrated Circuit (ASIC)": "Specialized computers designed for specific tasks, e.g., Bitcoin mining",
    "Arbitrage": "A strategy where investors buy a currency in one market and sell it at a higher price in another market for profit",
    "ASIC Resistant": "Cryptocurrency proof-of-work protocols designed to be resistant to Application-Specific Integrated Circuit (ASIC)",
    "Ask Me Anything (AMA)": "Sessions where individuals or companies conduct a Q&A session with users",
    "Atomic Swap": "Exchange of cryptocurrencies across different blockchains without intermediaries",
    "Automatic Replay Protection": "Upgrade implemented to prevent loss of funds from exchanges through replay attacks",
    "Bagholder": "A person holding a large quantity of cryptocurrency that is declining in value",
    "Bakkt": "Company specializing in Futures/Options contracts for cryptocurrencies developed by Intercontinental Exchange (ICE)",
    "Batch Auction": "Distribution of tokens to users based on their contribution to the pool",
    "Bearish": "Negative sentiment towards the market or an asset, anticipating downward price movement",
    "Bear Market": "A market trend characterized by a prolonged period of declining prices",
    "Bitcoin ATM": "A machine for buying or selling Bitcoin and sometimes other cryptocurrencies",
    "Bitcoin Evangelist": "Individuals passionate about spreading knowledge about Bitcoin",
    "Bitcoin Improvement Proposal (BIP)": "Proposals for introducing features or updates on the Bitcoin network",
    "BitLicense": "Business license issued by the New York State Department of Financial Services (NYSDFS) for cryptocurrency companies",
    "Block": "Collection of transactional data bundled together in a predetermined size on a blockchain",
    "Blockchain": "Decentralized, public ledger containing transactional information, as seen in Bitcoin",
    "Block Confirmation": "The number of confirmations a particular block has",
    "Block Explorer": "Applications or websites displaying information about transactions and blocks on a public blockchain network",
    "Block Height": "A number indicating the position of a particular block within a blockchain",
    "Block Reward": "A mechanism in a blockchain that incentivizes validators",
    "Bloodbath": "A market on a downtrend with many assets suffering from value depreciation",
    "Bots": "Software or programs that automatically trade based on preset behaviors",
    "Bounty": "Public tasks available for anyone to complete for a reward",
    "BUIDL": "An advice for investors to contribute to new projects on the blockchain rather than just holding cryptocurrencies",
    "Bullish": "Positive sentiment towards the market or an asset, anticipating upward price movement",
    "Bull Market": "A market trend characterized by a prolonged period of rising prices",
    "Burned Tokens": "Tokens sent to addresses with unknown private keys, rendering them unusable",
    "Buy/Sell Tax": "On-chain tax rate applied to the buying or selling of tokens, with a percentage going to a set address",
    "Buy the F***in Dip (BTFD)": "Encouraging rally by asset/cryptocurrency supporters to buy during a price decline",
    "Buy Wall": "Anomalously large buy order(s) at a single price point that acts as a 'wall' in the order book",
    "Byzantine Fault": "An error where a computer system does not know which component failed due to lack of information and continues to iterate on an instruction",
    "Byzantine Generals’ Problem": "A situation where consensus is required from untrusted members within a group",
    "Central Bank Digital Currency (CBDC)": "Digital fiat currency issued by central banks",
    "Centralized": "Organizational structure where a small group has control over the entire network",
    "Central Ledger": "Central data repository of a company or bank",
    "Circulating Supply": "Approximation of the number of coins or tokens available for public transactions",
    "Cloud Mining": "Mining on blockchains through rented processing power from hosting companies",
    "Cold Storage": "Offline storage of cryptocurrencies for added security, requiring physical access",
    "Cold Wallet": "Offline wallets that require physical access to specific devices",
    "Collateralized Debt Obligation (CDO)": "A derivative whose value is derived from another underlying asset and sold to institutional investors",
    "Composability": "The ability to combine different components of a software stack",
    "Consensus": "Achieved when all participants agree on the content of the next block to be added to the blockchain",
    "Crowdsale": "Auction with a fixed price per token sold on a first-come-first-serve basis",
    "Crypto Bubble": "Speculative period in cryptocurrencies with prices soaring before a market correction",
    "Cryptocurrency": "A form of digital currency utilizing cryptographic protocols for ownership and prevention of counterfeiting",
    "Cryptocurrency Act of 2020": "A bill aiming to clarify which federal agencies would regulate different types of crypto assets",
    "Cryptography": "The practice of using cryptographic techniques to secure information",
    "Custody": "Protective care or guardianship of an asset",
    "Daily Active Addresses (DAA)": "Number of addresses fulfilling the defined activity parameter on a given blockchain",
    "Dead Cat Bounce": "A short-lived price rally after a prolonged decline, followed by further decline",
    "Decentralized": "A system with no centralized points of failure or central authority figure",
    "Decentralized Applications (dApps)": "Applications that run on decentralized peer-to-peer networks",
    "Decentralized Autonomous Organization (DAO)": "Open source, decentralized systems that do not require centralized operators or controllers",
    "Decentralized Finance (DeFi)": "Building decentralized financial applications with no central authority and censorship resistance",
    "Decryption": "The process of converting encrypted data back to its original readable form",
    "Degen": "Cryptotrading without due diligence and research, akin to gambling",
    "Delegated Proof-of-Stake (dPOS)": "A consensus mechanism where selected members validate transactions and produce blocks",
    "Derivatives": "Financial instruments whose value is derived from an underlying asset or index",
    "Derivatives Market": "A market for instruments like futures or options whose value is derived from an underlying asset",
    "Difficulty": "A relative measure of how difficult it is to correctly guess a new block",
    "Directed Acyclic Graph (DAG)": "A data structure that branches out in one direction and never repeats",
    "Distributed Denial of Service (DDoS) Attack": "A common cyber-attack tactic where a perpetrator diverts large amounts of traffic towards a particular network or service in an effort to disrupt normal services.",
    "Distributed Ledger": "Ledgers whose data is stored and synced across a network of nodes.",
    "Distributed Ledger Technology (DLT)": "Describes the technology that enables distributed ledger.",
    "Dominance": "Typically refers to Bitcoins' market capitalization dominance.",
    "Double Spending": "Double spending refers to the act of spending digital currencies twice. This is most commonly applied on crypto exchanges by unscrupulous actors.",
    "Do Your Own Research (DYOR)": "An advice for investors to do their own research on the coins they wanted to invest in",
    "Dump": "A common term used to describe downward market movement, or to describe the action of selling an individual's holdings.",
    "Dusting Attack": "A new form of malicious activity in which hackers and scammers attempt to undermine the privacy of cryptocurrency users by sending little amounts of money to their wallets.",
    "Dutch Auction": "A Dutch Auction, also known as an 'inverted' auction, starts off with a high asking price that decays over time until a pre-determined floor price.",
    "EIP (Ethereum Improvement Proposal)": "Refers to improvement proposals for Ethereum, used to introduce features or any updates on the Ethereum network.",
    "Emission": "The speed/rate at which new coins are minted and released as dictated by the protocols written.",
    "Encryption": "In cryptography, encryption is a process of encoding information in the original form of information called plaintext via an algorithm called cipher. The encrypted message is now called ciphertext. Only authorized parties can decipher the ciphertext and convert it back to the original plaintext.",
    "Enterprise Ethereum Alliance (EEA)": "Enterprise Ethereum Alliance is made up of a group of Ethereum developers, corporations, as well as startups who are collaborating to find ways to use Ethereum for business applications.",
    "ERC-1155": "ERC-1155 token standard allows each token ID to represent both non-fungible (NFTs) and fungible tokens which may have their metadata, token supply and other attributes.",
    "ERC-20": "ERC-20 is one of the most widely used token standards in Ethereum to create fungible, exchangeable tokens.",
    "ERC-721": "ERC-721 is one of the most widely used token standards in Ethereum to create non-fungible, exchangeable tokens.",
    "Ethereum Name Service (ENS)": "Ethereum Name Service (ENS) is a look-up service that allows Ethereum users to find websites or send and receive funds via simple names.",
    "Ethereum Virtual Machine (EVM)": "Ethereum Virtual Machine (EVM) is the environment in which all smart contracts are executed.",
    "Exchange Traded Fund (ETF)": "An exchange-traded fund (ETF) is a form of security that tracks a collection of securities such as stocks, bonds, index or cryptocurrency but tradable like a single stock.",
    "Explain Like I'm Five (ELI5)": "To explain in such simple terms that even a five-year-old would be able to understand it.",
    "Externally Owned Accounts (EOA)": "Externally owned accounts (EOAs) are accounts that are controlled by a private key and have no coding associated with them.",
    "Faucet": "A faucet usually represents a site or app where a user can navigate to for small rewards repeated over time.",
    "Fear of Missing Out (FOMO)": "Refers to the feeling of apprehension for missing out on a potentially profitable investment opportunity and regretting it later. Generally an expression describing investors' fear of missing out the good timing of buying cryptocurrencies that could eventually be profitable.",
    "Fear, Uncertainty and Doubt (FUD)": "A strategy to dissuade people from buying a particular cryptocurrency by spreading false information.",
    "Fiat-Pegged Cryptocurrency": "Cryptocurrencies are pegged to an underlying asset.",
    "Flappening": "Flappening is a term used to describe Litecoin growing bigger and becoming more valuable than Bitcoin Cash (BCH). It is spawned from the term Flippening (used when another crypto overtakes Bitcoin).",
    "Frontrun": "To intercept a particularly large AMM buy order for the purpose of purchasing and reselling the assets back to the buyer before the order transaction is mined on the blockchain.",
    "Full Node": "Full Nodes are computers that verify the set of rules that are built into the protocols of a given cryptocurrency.",
    "Full Pay-Per-Share (FPPS)": "FPPS is quite similar to PPS; the only difference is that the pool will additionally pay a transaction fee incentive if the block is identified. FPPS is the same as PPS+.",
    "Fully Diluted Valuation": "Fully Diluted Valuation (FDV) is the market capitalization if the max supply of a coin is in circulation. The common mathematical formula used to calculate FDV is Current Price x Max Supply. Note that it can take 3, 5, 10 or more years before the FDV can be reached, depending on how the emission schedule is designed.",
    "Futures": "An agreement between two counterparties that obligates them to transact in the future based on the contract terms set.",
    "Gas": "A unit of measurement of the computational effort in conducting transactions or smart contracts on Ethereum blockchain.",
    "Gas Limit": "A term that refers to the maximum amount of units of gas a user is willing to spend on a transaction on Ethereum blockchain.",
    "Gas Price": "A term that refers to the amount of price a user is willing to pay for a transaction on Ethereum blockchain.",
    "Genesis Block": "It is the first block of data that is processed and validated to form a new blockchain, typically called as 'block 0' or 'block 1'.",
    "Goblin Town": "A term used to describe the market's persistent downtrend, synonymous with 'bear market'.",
    "Golden Cross": "It is a bullish signal in technical candlestick pattern by comparing two lines of short-term moving average and long-term average. It is a golden cross when the short-term moving average crosses above its long-term moving average.",
    "Graphical Processing Unit (GPU)": "They are chips dedicated to graphics processing or floating point operations, allowing to lighten the workload of the processors during applications usage such as video games.",
    "Gwei": "The monetary denomination of gas, involving Ether.",
    "Halving": "Event that serves to reduce in half the reward of the Proof-of-Work miners that operate in the blockchain network.",
    "Hard cap": "The maximum amount that an ICO will be raising.",
    "Hard Fork": "It is a permanent divergence of a blockchain into two blockchains. The original blockchain does not recognize the new version.",
    "Hash": "A hash function is an output code (unique and alphanumeric) that we obtain from an input string.",
    "Hashgraph": "Hashgraph is a distributed ledger system that has been compared to the blockchain idea as a continuation or successor.",
    "Hashrate": "Total processing power of a blockchain or what is the same, are the amount of hash values that can be made in a period of time.",
    "Hey Hey Hey": "A term made popular by Carlos Matos who was the spokesperson for the Bitconnect Ponzi. He used it frequently during Bitconnect events to rile up the crowd.",
    "HODL": "A crypto slang of saying holding the assets rather than selling it. A crypto slang encouraging investors to hold on to their assets rather than selling it.",
    "Hot Wallet": "It is a tool that stores your cryptocurrencies and is always connected to the internet.",
    "Hybrid PoW/PoS": "It is the allowance for both Proof-of-Stake and Proof-of-Work distribution consensus to work on the same network.",
    "Hyperledger (Hyperledger Foundation)": "Hyperledger is an open source collaborative effort to create blockchain technologies hosted by The Linux Foundation since 2016.",
    "IEO": "Initial Exchange Offering (IEO) is a spin-off of Initial Coin Offering (ICO), where the sale of tokens is conducted on an exchange rather than by the coin team themselves.",
    "Immutable": "A property characterized by inability to be changed and stays unchanged over time.",
    "Impermanent Loss": "Temporary loss of funds due to volatility leading to divergence in price between token pairs provided by liquidity providers.",
    "Initial Coin Offering (ICO)": "Initial Coin Offering (ICO) is the equivalent of Initial Public Offering (IPO), where a company/cryptocurrency venture raises funds through crowd sales.",
    "Internet of Things (IoT)": "It is a system that lets any devices that are connected to the internet communicate with each other without human-to-human or human-to-devices interactions.",
    "Interoperability": "Interoperability refers to the property of product/systems that are able to work with products/systems that are different without any restrictions.",
    "InterPlanetary File System (IPFS)": "The InterPlanetary File System (IPFS) is a peer-to-peer network and distributed file system protocol for storing and transferring data.",
    "IPO": "Initial Public Offering (IPO) refers to the process where a public company offers newly issued shares to the public and as a result raise capital from public investors.",
    "IYKYK": "Abbreviation for: if you know you know. The phrase implies that the user has dropped some sort of insider knowledge about a specific experience. Often, the post will have some callback to a particular experience that will instantly stand out to those who are 'in the know,' or ironically sharing commonly known information.",
    "Kimchi Premium": "The kimchi premium is the price difference between South Korean exchanges and other global exchanges for bitcoin.",
    "KYC (Know Your Customer)": "KYC stands for 'Know Your Customer', a process for business entities are required to verify its clients and assessing them.",
    "Ledger": "A record of financial transactions that cannot be changed, only appended with new transactions.",
    "Leverage": "It is an investment strategy to gain potential return of the investment by borrowing money from a broker (or in crypto, an exchange or platform) to trade.",
    "Lightning Network": "It is the 'second layer' or an off-chain of payment protocol that operates on top of a blockchain. Payments on this network do not need block confirmation and it will be instant.",
    "Limit Order / Limit Buy / Limit Sell":"Orders placed by traders to buy or sell a cryptocurrency when a certain price is reached.",
    "Liquidity": "The ease of which cryptocurrency can be bought and sold without impacting the overall market price.",
    "Liquid Proof of Stake (LPoS)": "A proof of stake consensus mechanism by Tezos that slightly differs from Delegated Proof of Stake.",
    "Mainnet": "It is the main network of Bitcoin, where the transactions of this cryptocurrency are registered and take place.",
    "Margin Call": "Margin call takes place when an investor's margin account falls below the required amount to stay afloat.",
    "Margin Trading": "It is a way of investing by borrowing money from a broker (or in crypto, an exchange or platform) to trade.",
    "Market capitalization (market cap)": "In Crypto, market cap is measured by multiplication of the circulating supply of tokens or currency and its current price.",
    "Market Maker": "A participant of the market who creates buy and sell orders.",
    "Market Order / Market Buy / Market Sell": "A market order is a buy or sell order of stocks or cryptocurrency at the best price available in the current market as soon as possible.",
    "Market Taker": "A participant of the market who buys and sells from currently existing orders.",
    "Masternodes": "Computers that are responsible for processing blockchain transactions and receive a reward when a block is mined.",
    "Mempool": "It is the abbreviation of Memory Pool. Set of unconfirmed transactions in a blockchain.",
    "Merkle Tree": "A Merkle tree is also known as a hash tree in cryptography. It is a tree where every leaf node is labeled with a cryptographic hash of a data block, and every non-leaf node is labeled with the hash of the labels of its child nodes. It is used to verify data stored within it and transferable in and between computers.",
    "Metaverse": "The Metaverse is a virtual space where users are able to interact with each other in a computer-generated environment.",
    "MicroBitcoin (uBTC)": "One millionth of a bitcoin or 0.000001 of a bitcoin. Microbitcoin is the abbreviation of uBTC and often misunderstood as the fork of Bitcoin.",
    "Microtransaction": "Microtransaction is a system that made very small payments possible in buying common digital goods and services, such as purchasing items in a game.",
    "Mineable": "A cryptocurrency is said to be 'mineable' when it has the system through which miners can be rewarded with newly-created cryptocurrencies for creating blocks.",
    "Miners": "Contributors to a blockchain taking part in the process of mining.",
    "Mining": "It is the process of the miners verifying and adding transaction records into a block.",
    "Mining Contract": "Another term for cloud mining, where users can rent or invest in mining capacity online.",
    "Mining Pool": "Combination of resources of several miners to obtain a higher mining power and thus achieve greater rewards for the opening of blocks.",
    "Mining Reward": "The reward resulting from contributing computing resources to process transactions.",
    "Mining Rig": "A dedicated hardware to mine.",
    "Mnemonic Phrase": "A mnemonic phrase (also known as mnemonic seed or seed phrase) is a list of words used in sequence to access or restore your cryptocurrency assets.",
    "Mnemonics": "Mnemonics are memory aids with a system such as letters or associations that help in recall.",
    "Money Printer Go Brrr": "A meme made to describe the US Fed printing an excessive amount of money to support the traditional financial market to avert the stock market crash during the COVID-19 coronavirus pandemic.",
    "Moon": "'Moon' or 'To the moon' is a crypto slang that describes an exclamation when the cryptocurrencies prices are rising, and when it hits the peak, the coin is said to be 'mooning'.",
    "Mt. Gox": "Mtgox or Mt. Gox was one of the first websites where users could take part in fiat-to-bitcoin exchange (and vice versa).",
    "Multisignal (multi-signature)": "They are wallets that require more than one key for transactions to be authorized.",
    "Node": "Within the blockchain network, the nodes are computers that connect to the network and have an updated copy of the blockchain",
    "Nonce": "Abbreviation for ‘number only used once’. It is of vital importance next to the hash in the verification of data from the Bitcoin blockchain network.",
    "Non-custodial": "It is a decentralized type-of-wallet, where the users owns its private keys.",
    "Non-Fungible Tokens (NFT)": "They are collectible elements within the Ethereum blockchain under ERC-721, where each token refers to a single element with a certain value",
    "Off-chain": "It refers to transactions occurring outside the blockchain and executed instantly.",
    "Offline Staking": "Staking without needing to be connected to the blockchain",
    "Open/Close": "The price at which a cryptocurrency opens at a time period, for example at the start of the day; the price at which a cryptocurrency closes at a time period, for example at the end of the day.",
    "Open Source": "Open-source software is a type of software released under a license in which the copyright holder grants users the rights to study, change, and distribute the software to anyone and for any purpose.",
    "Option": "It is a financial instrument that refers to a contract offering the buyer the right to buy or sell an underlying asset at a specified price and time.",
    "Oracles": "In the context of crypto, oracles refers to services which verify real-world and provide data to blockchains/smart contracts.",
    "Order Book": "An electronic list of all buy and sell orders in an exchange",
    "Over The Counter (OTC)": "It refers to the process that cryptocurrencies are being traded outside exchange and it is done directly between two parties",
    "Pay-Per-Last N Shares (PPLNS)": "PPLNS system only pays miners after the pool has discovered the block. This means you'll only be compensated once the block has been discovered.",
    "Pay-Per-Share (PPS)": "You are compensated for each valid share that you contribute. Each share is worth a set amount of cryptocurrency that may be mined.",
    "Peer to Peer": "A communication protocol that does not require a central hub",
    "Permissioned Blockchain": "It is a private blockchain where the nodes must be previously authorized by a central entity.",
    "PFP": "It means both 'profile pic' and 'picture for proof'.",
    "Proof of Stake (PoS)": "A consensus algorithm that assigns block validation queue based on the coins/tokens locked in by the validator.",
    "Proof of Work (PoW)": "A consensus algorithm in which a block is validated via mathematical hashing.",
    "Protocol": "The set of rules in a network in which participating members comply to allow proper communication.",
    "Public Blockchain": "An open sourced blockchain where participation is public and permissionless.",
    "Public Keys": "The alphanumeric string which serves as a public receiving address in cryptocurrencies.",
    "Pump and Dump Scheme": "A market manipulation method to drive up the price of an asset before profiting by driving it back down.",
    "QR Code": "Abbreviation 'Quick Response Code', QR code is a machine-readable optical label that stores up to 3Kb of data.",
    "Reddit r/CryptoCurrency Moon": "Moons are a new way for people to be rewarded for their contributions to r/CryptoCurrency.",
    "REKT": "A shorthand slang for “wrecked”, typically describes bad trades that result in losses.",
    "Relative Strength Index (RSI)": "Relative Strength Index (RSI) is a popular technical indicator used to analyze financial markets.",
    "Replay Attack": "A replay attack is a form of network attack when valid data transmission is fraudulently intercepted, then delayed or resent to mislead the receiver into doing what the hacker wants.",
    "Ring Signature": "A type of digital signature performed in a group where it becomes impossible to determine which member's key in the group was used for the digital signature.",
    "ROI": "Short for “Return on Investment”, the ratio between the net profit and cost of investing.",
    "Rug Pull": "Sudden removal of liquidity which typically leads to asset prices crashing from the lack of liquidity to absorb buy/sells.",
    "Salt (cryptography)": "In cryptography, a salt is the additional random input that is added to password or passphrase to make the password hash unique.",
    "Satoshi": "A unit measure for the smallest divisible unit of a bitcoin. 1 bitcoin is equal to 100 Million Satoshi.",
    "Satoshi Nakamoto": "The pseudonym used in publishing the Bitcoin Whitepaper. Identity is unknown.",
    "Scrypt": "One of the hashing algorithms used in proof-of-work protocol, scrypt requires more memory in order to perform mining functions.",
    "Second-Layer Solutions": "Secondary network or framework built atop an existing blockchain to address transaction speed and scalability issues.",
    "Secure Asset Fund for Users (SAFU)": "A feature created by Binance which contains reserve funds that can be used to reimburse users in case of a catastrophic event (e.g., exchange hack).",
    "Securities and Exchange Commission (SEC)": "U.S. Securities and Exchange Commission, an independent agency of the US Federal government which oversees federal securities laws, proposing securities rules, and regulating the securities industry.",
    "Seed": "A value used to initiate generation of pseudorandom number, usually a string of 12 common English words.",
    "Segregated Witness (SegWit)": "A soft fork implementation to change the Bitcoin Protocol's transaction format to address Bitcoin's scalability issues whilst introducing new features.",
    "Sell wall": "Anomalously large sell order(s) at a single price point that reflects as a 'wall' in the order book.",
    "SHA-256": "Abbreviation of 'Secure Hashing Algorithm - 256', SHA-256 is part of the SHA2 that allows one-way hashing of any data into a 64 character string.",
    "Sharding": "A form of database partitioning which breaks up data into smaller segments.",
    "Shilling": "One who poses as an enthusiastic customer to swindle others as a form of covert advertising.",
    "Shitcoin": "A coin with no obvious potential value or usage.",
    "Side Chain": "A separate blockchain ledger that runs parallel with the primary blockchain.",
    "Sim Swapping": "It is a tactic where a hacker overtakes the mobile phone to exploit the two-factor authentication and two-step verification.",
    "Smart contracts": "Self-executing contracts on the blockchain without needing human executors or notary.",
    "Soft Cap": "Targeted fundraising limit of an ICO",
    "Soft Fork": "A backward-compatible update to a decentralized blockchain protocol.",
    "Software Development Kit (SDK)": "It is a collection of software development tools in one package installation. It is designed to help develop applications for a specific device or operating system (OS).",
    "Solidity": "Object-oriented programming language used in various smart contract blockchains.",
    "Solo Staker": "A Qtum PoS miner using their own coins for staking. Qtum blockchain launched with Solo Stakers and will continue to have this available after offline staking launches.",
    "Stablecoin": "Cryptocurrency with a price peg to fiat currencies or commodity.",
    "Staking": "The state of locking-in a significant amount of token to participate as a validator of a Proof-of-Stake network.",
    "Stale Block": "Double mined blocks that are not included in the blockchain.",
    "State Channel": "Secondary payment channel occurring off-chain",
    "STO": "Security Token Offering (STO) refers to a public offering for tokenized digital securities, or in short security tokens traded in cryptocurrency exchanges.",
    "Stop-loss Order": "Conditional market order to sell at the next available price, executed if the price of an asset falls below set-upon limit",
    "Super Staker": "A Qtum Core wallet (full node) providing Proof of Stake for delegated addresses, and keeping a small part of each block reward as their fee for providing the staking services.",
    "Tangle": "The name for IOTA's Directed acyclic graph (DAG) based transaction settlement layer.",
    "Testnet": "Shorthand for 'Test Network', testnets are staging areas for experimenting new blockchain features.",
    "Ticker": "A ticker is a stock or asset symbol that abbreviates the asset name and it can be used as an identifier of the asset.",
    "Token": "Blockchain based unit of value issued by an organization, which grants token holders a right to participate in a network.",
    "Token Burn": "An event in which tokens are verifiably removed permanently removed from circulation.",
    "Token Generation Event (TGE)": "An event in which new tokens (usually on a smart contract platform) are created and distributed to the public.",
    "Total Supply": "All the tokens and coins that will exist in a cryptocurrency network.",
    "Total Value Locked": "Total Value Locked (TVL) represents the number of assets that are currently staked in a protocol or the total quantity of underlying amount of funds that a DeFi protocol has secured.",
    "Trading Volume": "The amount of the cryptocurrency that has been traded in the last 24 hours.",
    "Transaction Fee": "A payment to the network for performing a transaction to be recorded on the blockchain.",
    "Transactions Per Second (TPS)": "It is the number of transactions done per second. For example, there are 10 transactions of Bitcoin done in 1-minute. The TPS would be 10 transactions/60 seconds = ~0.17 TPS.",
    "Trustless": "Entirely verifiable, without needing to trust or assume an action is done completely and in good faith.",
    "Turing-Complete": "A 'turing complete' code or blockchain refers to the ability to read program-written codes.",
    "Unspent Transaction Output": "(abbr. 'UTXO') Coins that are unspent in the wallet. UTXO virtually represents the cryptocurrency one owns in the wallet.",
    "UTC Time": "'Universal Time Coordinated', can be used interchangeably with Greenwich Mean Time (GMT).",
    "Utility Token": "Cryptocurrency tokens with specific utilities on a network besides being used as a medium of exchange and investment vehicle.",
    "Validator": "A block-signing participant of a Proof of Stake blockchain network, whom have significant tokens staked on the network.",
    "Variable Buy/Sell Tax": "On-chain buy sell tax rate that is not fixed, whereby it is possible for contract owners to change at will.",
    "Venture Capital": "Capital (funds) that is invested in a company that needs a substantial pool of funds to initiate.",
    "Virtual AMM (vAMM)": "The vAMM functions similarly like an AMM but does not contain an actual asset pool.",
    "Wallet": "Software client that handles storage of cryptocurrencies and allows users to send cryptocurrencies.",
    "Wallet Address": "The address in which cryptocurrency can be stored, sent to and received.",
    "Wash Trade": "Meaningless back and forth trading between a single party with the aim of inflating trade volume.",
    "Watchlist": "A personally defined list of values to watch over for activity or changes.",
    "Web3 Wallet": "Web3 Wallet is the software that allows you to interact with web 3.0.",
    "Wei": "The smallest fraction of an Ether, with each Ether to 1000000000000000000 Wei.",
    "Whale": "Someone who holds an enormous amount of cryptocurrency and has the ability to sway the market.",
    "When Lambo": "An expression used by investors to ask when the value of their investment could buy them a Lamborghini.",
    "When Moon": "An expression used by investors to ask when the price of a coin would hit a peak.",
    "Whitelist": "List of approved participants that will be given access to a token sale (ICO, IEO, STO etc...).",
    "Whitepaper": "An introductory paper to concisely explain an issue and a possible solution to the issue.",
    "Yield Farming": "Yield farming involves putting cryptocurrency into a DeFi protocol to collect interest on trading fees.",
    "YTD": "Acronym for Year-to-date.",
    "Zero Confirmation Transaction": "Another name for 'unconfirmed transaction'.",
    "Zero Knowledge Proof": "Cryptographic proof for 2 parties to verify a value without revealing what the value is.",
}
  